name: 'actionlint with reviewdog'
description: 'run actionlint with reviewdog'
author: '@shogo82148'
inputs:
  github_token:
    description: 'GITHUB_TOKEN'
    default: '${{ github.token }}'
  workdir:
    description: 'Working directory relative to the root directory.'
    default: '.'
  ### Flags for reviewdog ###
  tool_name:
    description: 'Tool name to use for reviewdog reporter.'
    default: 'actionlint'
  level:
    description: 'Report level for reviewdog [info,warning,error].'
    default: 'error'
  reporter:
    description: 'Reporter of reviewdog command [github-check,github-pr-review,github-pr-check,sarif].'
    default: 'github-check'
  filter_mode:
    description: |
      Filtering mode for the reviewdog command [added,diff_context,file,nofilter].
      Default is `file` except that sarif reporter uses `nofilter`.
    default: 'file'
  fail_level:
    description: |
      If set to `none`, always use exit code 0 for reviewdog. Otherwise, exit code 1 for reviewdog if it finds at least 1 issue with severity greater than or equal to the given level.
      Possible values: [none,any,info,warning,error]
      Default is `none`.
    default: 'none'
  reviewdog_flags:
    description: 'Additional reviewdog flags.'
    default: ''
  actionlint_flags:
    description: 'Additional actionlint flags'
    default: ''
    required: false
  output_dir:
    description: 'Output directory of reviewdog result. Useful for -reporter=sarif'
    default: '../reviewdog-results'
runs:
  using: 'composite'
  steps:
    - uses: reviewdog/action-setup@d8edfce3dd5e1ec6978745e801f9c50b5ef80252 # v1.4.0
      with:
        reviewdog_version: v0.21.0
    - run: $GITHUB_ACTION_PATH/script.sh
      shell: bash
      env:
        ACTIONLINT_VERSION: 1.7.10
        SHELLCHECK_VERSION: 0.11.0
        # INPUT_<VARIABLE_NAME> is not available in Composite run steps
        # https://github.community/t/input-variable-name-is-not-available-in-composite-run-steps/127611
        INPUT_GITHUB_TOKEN: ${{ inputs.github_token }}
        INPUT_WORKDIR: ${{ inputs.workdir }}
        INPUT_TOOL_NAME: ${{ inputs.tool_name }}
        INPUT_LEVEL: ${{ inputs.level }}
        INPUT_REPORTER: ${{ inputs.reporter }}
        INPUT_FILTER_MODE: ${{ inputs.filter_mode }}
        INPUT_FAIL_LEVEL: ${{ inputs.fail_level }}
        INPUT_REVIEWDOG_FLAGS: ${{ inputs.reviewdog_flags }}
        INPUT_ACTIONLINT_FLAGS: ${{ inputs.actionlint_flags }}
        INPUT_OUTPUT_DIR: ${{ inputs.output_dir }}
    - if: inputs.reporter == 'sarif'
      uses: github/codeql-action/upload-sarif@df559355d593797519d70b90fc8edd5db049e7a2 # v3.29.9
      with:
        sarif_file: ${{ inputs.output_dir }}
branding:
  color: red
  icon: check-circle
