name: reviewdog
on: [pull_request]

permissions:
  contents: read
  checks: write
  pull-requests: write
  issues: write

jobs:
  actionlint:
    name: runner / actionlint
    strategy:
      matrix:
        runs-on:
          - ubuntu-latest
          - ubuntu-slim
          - windows-latest
          - macos-latest
    runs-on: ${{ matrix.runs-on }}
    steps:
      - uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0
      - name: actionlint
        uses: ./
        with:
          tool_name: actionlint

  reviewdog:
    name: runner / reviewdog
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0
      - name: actionlint w/ reviewdog
        id: actionlint
        continue-on-error: true
        uses: ./
        with:
          actionlint_flags: examples/broken-workflow.yml
          reporter: github-pr-review
          filter_mode: nofilter
          fail_level: any
          tool_name: reviewdog
      - name: Expect reviewdog to find issues
        run: |
          if [ "${{ steps.actionlint.outcome }}" != "failure" ]; then
            echo "Expected failure but got ${{ steps.actionlint.outcome }}"
            exit 1
          fi

  shellcheck:
    name: runner / shellcheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0
      - name: actionlint w/ shellcheck
        id: actionlint
        continue-on-error: true
        uses: ./
        with:
          actionlint_flags: examples/shellcheck.yml
          reporter: github-pr-review
          filter_mode: nofilter
          fail_level: any
          tool_name: shellcheck
      - name: Expect reviewdog to find issues
        run: |
          if [ "${{ steps.actionlint.outcome }}" != "failure" ]; then
            echo "Expected failure but got ${{ steps.actionlint.outcome }}"
            exit 1
          fi

  pyflakes:
    name: runner / pyflakes
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0
      - name: actionlint w/ pyflakes
        id: actionlint
        continue-on-error: true
        uses: ./
        with:
          actionlint_flags: examples/pyflakes.yml
          reporter: github-pr-review
          filter_mode: nofilter
          fail_level: any
          tool_name: pyflakes
      - name: Expect reviewdog to find issues
        run: |
          if [ "${{ steps.actionlint.outcome }}" != "failure" ]; then
            echo "Expected failure but got ${{ steps.actionlint.outcome }}"
            exit 1
          fi
